### ISSUE TITLE
Error while syncing gradle in Android Studio

### ISSUE THREAD

**Issue by bramvdbogaerde** [florent37/Carpaccio#2]
I get the following error if I add this to my project in my build.gradle file:
Error:Module version com.github.florent37:carpacciocontrollers:1.0.0 depends on libraries but is not a library itself

**Comment by florent37** [comment]
Thx, I'm working on it :+1:

**Comment by florent37** [comment]
gradle don't like the dependencies with my 2 modules, so I merged them
I'll see in a future version if I can separate them

you can now use : 
	compile ('com.github.florent37:carpaccio:1.0.0@aar'){
	    transitive=true
	}
