### ISSUE TITLE
Android Studio Preview not working

### ISSUE THREAD

**Issue by KhoaSuperman** [florent37/Carpaccio#3]
Hi Florent,
Firstly, thank so much for awesome work, I really love it.
I checkout project then try to run on my own but there's something not correct

Here is design mode:
![screen shot 2015-07-31 at 9 29 36 am](https://cloud.githubusercontent.com/assets/8596226/8999603/01d73224-3767-11e5-803d-221303cf78c2.png)

In activity:
![screen shot 2015-07-31 at 9 32 45 am](https://cloud.githubusercontent.com/assets/8596226/8999612/22b185da-3767-11e5-9b7f-5dcb70cf5bf3.png)

Image preview and set text seems not working. Can you help me to find out what going not correct ?
Thanks :)

**Comment by florent37** [comment]
Hi, sometimes the preview don't do the work the first time, click on the refresh button, it should work :)


<img width="36" alt="capture d ecran 2015-08-01 a 00 01 02" src="https://cloud.githubusercontent.com/assets/5754972/9018574/6b64644a-37e0-11e5-8ba0-3e10d8fa5e84.png">

**Comment by intrications** [comment]
It would be worth adding a (large?) note to the README and/or Wiki because I had this problem and had almost given up on the library before seeing this issue.
