### ISSUE TITLE
Edit recyclerview items

### ISSUE THREAD

**Issue by kegita** [florent37/Carpaccio#5]
Hello! How can access list mapped to Carpaccio and notifiydatasetchanged??? Thanks

**Comment by florent37** [comment]
Hi, you can use `carpaccio.getMappedList("user")`if you used `mapList("user")`
I'm doin the wiki, so don't hesitate to send me questions, if it's implemented I'll put the answer here, else I'll implement it

**Comment by florent37** [comment]
if you want to notify dataset changed `carpaccio.getAdapter("user"). notifiydatasetchanged``

**Comment by kegita** [comment]
Ok, thanks! Another problem: i have edited an user of an arraylist that i have passed to maplist. Before doing carpaccio.getAdapter("user").notifyDataSetChanged(), i have to set the edited user in the correct position of the list. Is there a method to do that o i have to cycling entire list and do a comparison by POJO attribute to find the correct position? Thanks

**Comment by florent37** [comment]
You can use list.indexOf
